In [1]:
import pandas as pd
import config as cfg

In [3]:
task1_train = pd.read_feather(cfg.FILE_TASK1_TRAIN)
task1_train

            id                                                seq  isenzyme
0       Q3J1A3  MADKSDLGYTGLTDEQAQELHSVYMSGLWLFSAVAIVAHLAVYIWRPWF     False
1       P02157  MGLSDGEWQLVLNVWGKVEADLAGHGQEVLIRLFKGHPETLEKFDK...     False
2       P02178  MVLSDAEWQLVLNIWAKVEADVAGHGQDILIRLFKGHPETLEKFDK...     False
3       P02194  MGLSDGEWQLVLNIWGKVETDEGGHGKDVLIRLFKGHPETLEKFDK...     False
4       P01915  MVWLPRVPCVAAVILLLTVLSPPVALVRDTRPRFLEYVTSECHFYN...     False
...        ...                                                ...       ...
469129  Q21221  MSSGAPSGSSMSSTPGSPPPRAGGPNSVSFKDLCCLFCCPPFPSSI...      True
469130  Q6QJ72  MSRLLLPKLFSISRTQVPAASLFNNLYRRHKRFVHWTSKMSTDSVR...      True
469131  C0HL68     GLFSKPAGKGIKNLIPKGVKHIGKEVGKDVIRTGIDVAGCKIKGEC     False
469132  C0HK74  GSICLEPKVVGPCTAYFPRFYFDSETGKCTPFIYGGCEGNGNNFET...     False
469133  D9XDR8  MAKMSTTHEEIALAGPDGIPAVDLRDLIDAQLYMPFPFERNPHASE...      True

[469134 rows x 3 columns]

In [4]:
task1_train.sort_values(by=['id'])

,id,seq,isenzyme
463336,A0A023GPI8,ADTIVAVELDTYPNTDIGDPSYPHIGIDIKSVRSKKTAKWNMQNGK...,False
460222,A0A023GPJ0,MFGIFSKGEPVSMEGELVQPSSIVINDYEEELHLPLSYWDIKDYKN...,False
459244,A0A023PXA5,MLLSELVATASSLPYTAISIHNNCRVPAARHIHHGCRYFHGPPVMH...,False
459238,A0A023PXB0,MFINGFVNYPVRTPPNDLLQVVLHGFLRCPLDGSQVDSIGIGHTVH...,False
459398,A0A023PXB5,MFALIISSKGKTSGFFFNSSFSSSALVGIAPLTAYSALVTPVFKSF...,False
...,...,...,...
465917,X5IWS1,MKLTCVVIVAALLLTACQLITALDCGGTQKHRALRSTIKLSLLRQH...,False
465600,X5JA13,MTEGIRARGPRSSSVNSVPLILDIEDFKGDFSFDALFGNLVNDLLP...,False
465610,X5JB51,MTERIRARGPRSSSVNSVPLILDIEDFKGDFSFDALFGNLVNDLLP...,False
460957,X5M5N0,MPDSITNGGRPPAPPSSVSSTTASTTGNFGTRRRLVNRIKKVDELH...,True
461064,X5M8U1,MLFLRLFIFTPFLILANCQARRTIKVGLLFVQNVSSLQVGIGYRTS...,True